language: common-lisp
sudo: false

addons:
  apt:
    packages:
    - zip

env:
  global:
  - GAMEKIT_SYSTEM_NAME: sokob-ant
  - GAMEKIT_APPLICATION_PACKAGE: sokob-ant
  - GAMEKIT_APPLICATION_MAIN_CLASS: sokob-ant
  - PATH: ~/.bodge/bin/:$PATH
  - GAMEKIT_TARGET_PACKAGE: $GAMEKIT_SYSTEM_NAME-x86-64-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.zip
  - GAMEKIT_BUILD_DIR: /tmp/$GAMEKIT_SYSTEM_NAME
  - secure: "f3h7Wsev68U0AmF7rgWdREBTctDIQfkzoHOt5lBCQtYvIC9uiV2kYejPSbsztRMkiqgULscGGI7rZtELVSS9rtqJ963s9IpljFOM55mrFHINET9DY2FMn1h6sufnzks3omNrSxfyGPlhgUxIlr9X9/7qDf6JUuoQK3blOoTWAEO6XlOofsONaSAl1zAk0vXqGw+j8BQ2J3SI2BRsdj5YdCP617SraQqAuxgqtddQO1ywhZPaGuOBNTOiJWZLcGzxA74fEyNTGpNMkE9BEoTv7MliRGfdQefn5qBUtl8q3+67zATG4FEnFEvrpH/a7xQfvD6fiVg6b31PNHgC97Dyaf5vjh3H5cXJ4pn3xUtKUa0T077ELUjVaOa0d/IuEenuocW5jB7k7TQ+crIIZ0nFXnFP7/+KgntiPN0nZ0i5bcrA+7+mZD3VjQwKUNocVM/9hzt7y7tNTCJ8Iz+CLvpuHNtmM4DdKyHdasm64Sy7BAA2pwPru2Bt5Di6eNp2VygQumcGgfAxzOZzMAiKtv6VXH7lCZ8fPcj1gz+FIK7oD/xc/7jc+bdwfvs6m3R/MGmEatVQiS6dzN2sjJvZrLzz69Vz24giKpwDB/9yNNEpORpvIgtFG9PWcKBff1zHtWBAPCOywM6eVuppKc//ClSrmI7RkUs34nRz86DiHLYAIYg="


branches:
  only:
    - "/^v\\d+(\\.\\d+)+$/"

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install git-lfs; fi
  - curl -L http://bodge.borodust.org/files/install.sh | sh
  - git lfs install && git lfs pull
  - lisp install-testing-dist

script:
  - >
    lisp build-gamekit-system
    $GAMEKIT_SYSTEM_NAME $GAMEKIT_APPLICATION_PACKAGE $GAMEKIT_APPLICATION_MAIN_CLASS
    $TRAVIS_BUILD_DIR
    $GAMEKIT_BUILD_DIR

before_deploy:
  - mv "$GAMEKIT_BUILD_DIR/$GAMEKIT_SYSTEM_NAME.zip" $GAMEKIT_TARGET_PACKAGE

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file: $GAMEKIT_TARGET_PACKAGE
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
